name: Pull Request
on: pull_request
jobs:
  test:
     strategy:
       matrix:
         go-version: [1.13.x]
         platform: [ubuntu-latest]
     runs-on: ${{ matrix.platform }}
     steps:
       - name: Install Go
         uses: actions/setup-go@v1
         with:
           go-version: ${{ matrix.go-version }}
       - name: Checkout code
         uses: actions/checkout@v1
       - name: run unit test
         run: make test
       - name: Generate coverage report
         run: make coverage
       - name: Upload coverage to Codecov
         if: runner.os == 'Linux'
         uses: codecov/codecov-action@v1.0.3
         with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
         
